services:
  caddy:
    image: caddy:2.10
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/tank/teem/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /mnt/tank/teem/caddy/data:/data
      - /mnt/tank/teem/caddy/config:/config
